services:
  db:
    image: postgres:16-alpine
    container_name: postgres_outbox

    restart: always

    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: outbox_db

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"

    networks:
      - outbox-network

volumes:
  pgdata:

networks:
  outbox-network:
    external: true