version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"  
    env_file:
      - .env
    environment:
      DB_HOST: postgres_outbox
      DB_NAME: outbox_db
      DB_USER: myuser
      DB_PASS: mypassword
      DB_PORT: 5432
      PORT: 3000
    networks:
      - outbox-network  

networks:
  outbox-network:
    external: true